export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BAKERY_OWNER: 'BAKERY_OWNER',
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
  CUSTOMER: 'CUSTOMER',
}

export const ROLE_HIERARCHY = [
  ROLES.SUPER_ADMIN,
  ROLES.BAKERY_OWNER,
  ROLES.ADMIN,
  ROLES.STAFF,
  ROLES.CUSTOMER,
]
